#Primera parte: Instalación de RedPanda-Base
---
version: "3.9"
networks:
  redpanda_network:
    driver: bridge
services:
  redpanda-ksql:
    command:
      - redpanda
      - start
      - --smp
      - '1'
      - --reserve-memory
      - 0M
      - --overprovisioned
      - --set
      - redpanda.cluster_id=turning-red
      - --set 
      - redpanda.enable_idempotence=true
      - --set 
      - redpanda.enable_transactions=true
      - --set
      - redpanda.auto_create_topics_enabled=true
      - --node-id
      - '0'
      - --kafka-addr PLAINTEXT://0.0.0.0:29092,OUTSIDE://0.0.0.0:9092
      - --advertise-kafka-addr PLAINTEXT://redpanda-ksql:29092,OUTSIDE://localhost:9092
    image: docker.vectorized.io/vectorized/redpanda:v21.11.11
    container_name: redpanda-ksql
    networks:
      - redpanda_network
    ports:
      - 29092:29092
      - 9092:9092

#Segunda Parte: Instalación de RedPanda-Console
  console:
    container_name: redpanda-consola
    image: docker.redpanda.com/redpandadata/console:v2.3.0
    networks:
      - redpanda_network
    entrypoint: /bin/sh
    command: -c 'echo "$$CONSOLE_CONFIG_FILE" > /tmp/config.yml; /app/console'
    environment:
      CONFIG_FILEPATH: /tmp/config.yml
      CONSOLE_CONFIG_FILE: |
        kafka:
          brokers: ["redpanda-ksql:29092"]
          schemaRegistry:
            enabled: true
            urls: ["http://redpanda-ksql:8081"]
        redpanda:
          adminApi:
            enabled: true
            urls: ["http://redpanda-ksql:9644"]
    ports:
      - 8080:8080
    depends_on:
      - redpanda-ksql

#Tercera Parte: Definición de KSQL en Redpanda
  ksqldb-server:
    image: confluentinc/cp-ksqldb-server:6.0.14
    networks:
      - redpanda_network
    hostname: ksqldb-serverDB
    container_name: ksqldb-server
    depends_on:
      - redpanda-ksql
    ports:
      - "8088:8088"
    environment:
      KSQL_LISTENERS: "http://0.0.0.0:8088"
      KSQL_BOOTSTRAP_SERVERS: "redpanda-ksql:29092"
      KSQL_KSQL_SCHEMA_REGISTRY_URL: "http://schema-registry:8081"
      KSQL_KSQL_LOGGING_PROCESSING_STREAM_AUTO_CREATE: "true"
      KSQL_KSQL_LOGGING_PROCESSING_TOPIC_AUTO_CREATE: "true"

  ksqldb-cli:
    image: confluentinc/cp-ksqldb-cli:6.0.14
    networks:
      - redpanda_network
    container_name: ksqldb-client
    depends_on:
      - redpanda-ksql
      - ksqldb-server
    entrypoint: /bin/sh
    tty: true